### ISSUE TITLE
Create Your Own DEV Branch

### ISSUE THREAD

**Issue by mbrandon32** [chingu-voyage5/Toucans-Team-8#12]
Making it easier, please setup your own branches to work under.  Merge the master to it when you start working on yours then error checker with make sure that we don't accidentally over write each others code.  -  Cheers

**Comment by abutler911** [comment]
My dev branch is created.

**Comment by TheSharpReport** [comment]
Created mine as well. Made the rookie mistake of merging a super minor change to the master branch. I reverted that and have set up my dev branch.
